[workspace]

members = [
    "web-api",
    "web_commons",
    "mc-server"
]

[workspace.dependencies]
anyhow = "1.0.66"
log = "0.4.17"
chrono = "0.4.23"
fern = "0.6.1"
serde = "1.0.151"
serde_derive = "1.0.151"