name: Checkout Production

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy Production Service Matrix
    uses: ./local_workflows/deploy-service-matrix.yaml
    secrets: inherit
    with:
      build-path: "release"
      build-profile: "release"
      k8s-deployment-ns: "production"
      k8s-ingress-suffix: "fixed.codes"
      k8s-ingress-tls-name: "wildcard-fixed-codes-tls"
      tag-prefix: "prd-"