name: Checkout Production

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build_and_deploy:
    name: Deploy Development Service Matrix
    secrets: inherit
    uses: ./.github/workflows/deploy-service-matrix.yaml
    with:
      build-path: "release"
      build-profile: "release"
      k8s-deployment-ns: "production"
      k8s-ingress-suffix: "fixed.codes"
      k8s-ingress-tls-name: "wildcard-fixed-codes-tls"
      tag-prefix: "prd-"
