name: Checkout Develop

on:
  push:
    branches:
      - develop
  pull_request:
    types:
      - opened
      - edited
      - updated
    branches:
      - develop
  workflow_dispatch:

jobs:
  build_and_deploy:
    name: Deploy Development Service Matrix
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (v3)
        uses: actions/checkout@v3
      - name: Deploy Service Matrix
        uses: ./github/actions/deploy-service-matrix.yaml
          with:
            build-path: "debug"
            build-profile: "dev"
            k8s-deployment-ns: "develop"
            k8s-ingress-suffix: "dev.fixed.codes"
            k8s-ingress-tls-name: "wildcard-dev-fixed-codes-tls"
            tag-prefix: "dev-"