name: Checkout Develop

on:
  push:
    branches:
      - develop
  pull_request:
    types:
      - edited
      - updated
    branches:
      - develop
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy Development Service Matrix
    uses: ./local_workflows/deploy-service-matrix.yaml
    secrets: inherit
    with:
      build-path: "debug"
      build-profile: "dev"
      k8s-deployment-ns: "develop"
      k8s-ingress-suffix: "dev.fixed.codes"
      k8s-ingress-tls-name: "wildcard-dev-fixed-codes-tls"
      tag-prefix: "dev-"