name: Build and Deploy Service Matrix

on:
  workflow_call:
    inputs:
      build-path:
        description: "Maps to the docker file BUILD_PATH argument"
        required: true
        type: string
      build-profile:
        description: "Maps to the docker file BUILD_PROFILE argument"
        required: true
        type: string
      k8s-deployment-ns:
        description: "Kubernetes deployment namespace"
        required: true
        type: string
      k8s-ingress-suffix:
        description: "Kubernetes ingress suffix"
        required: true
        type: string
      k8s-ingress-tls-name:
        description: "Kubernetes ingress TLS name"
        required: true
        type: string
      tag-prefix:
        description: "Prefix used for docker image tag"
        required: true
        type: string

jobs:
  import_matrix_info:
    runs-on: ubuntu-latest
    name: Import Matrix Info
    outputs:
      matrix_info: ${{ steps.export-json.outputs.matrix_info }}
    steps:
      - name: Export Deploy Json
        id: export-json
        run: |
          ls ${GITHUB_WORKSPACE} -la
          content=`cat ${GITHUB_WORKSPACE}/apps.json`
          content="${content//'%'/'%25'}"
          content="${content//$'\n'/'%0A'}"
          content="${content//$'\r'/'%0D'}"
          echo "::set-output name=matrix_info::$content"
  build_deploy_matrix:
    needs: [ import_matrix_info ]
    name: Build and Deploy Service Matrix
    secrets: inherit
    strategy:
      matrix:
        app: ${{ fromJson(needs.import_matrix_info.outputs.matrix_info) }}
    uses: ./.github/workflows/deploy-service.yaml
    with:
      build-path: ${{ inputs.build-path }}
      build-profile: ${{ inputs.build-profile }}
      app-name: ${{ matrix.app }}
      tag-prefix: ${{ inputs.tag-prefix }}
      k8s-deployment-ns: ${{ inputs.k8s-deployment-ns }}
      k8s-ingress-suffix: ${{ inputs.k8s-ingress-suffix }}
      k8s-ingress-tls-name: ${{ inputs.k8s-ingress-tls-name }}