name: Deploy to Kubernetes

on:
  workflow_call:
    inputs:
      app-name:
        description: "The app's name."
        required: true
        type: string
      helm-chart:
        description: "Helm chart name."
        required: true
        type: string
      image-tag-prefix:
        description: "Prefix used for docker image tag."
        required: true
        type: string
      k8s-deployment-ns:
        description: "Kubernetes deployment namespace"
        required: true
        type: string
      k8s-ingress-name:
        description: "Kubernetes ingress name"
        required: true
        type: string
      k8s-ingress-tls-name:
        description: "Kubernetes ingress TLS name"
        required: true
        type: string
      service-type:
        description: "Kubernetes service type"
        required: false
        type: string
        default: "ClusterIP"
      service-port:
        description: "Kubernetes service port"
        required: false
        type: number
        default: 3000
      service-target-port:
        description: "Kubernetes service target port"
        required: false
        type: string
        default: http

env:
  IMAGE_REPOSITORY: ghcr.io/coreyshupe/fixed.codes

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy to Kubernetes
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_TOKEN }}
      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: latest
          token: ${{ secrets.GITHUB_TOKEN }}
        id: install
      - name: Save DigitalOcean kubeconfig with short-lived credentials
        run: doctl kubernetes cluster kubeconfig save --expiry-seconds 600 ${{ secrets.DIGITALOCEAN_K8S_CLUSTER }}
      - name: Set outputs
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      - name: Helm install onto cluster
        run: |-
          helm upgrade --install --atomic --wait --timeout 600s --create-namespace ${{ inputs.app-name }} deploy/charts/${{ inputs.helm-chart }} \
          --namespace ${{ inputs.k8s-deployment-ns }} \
          --set fullnameOverride=${{ inputs.app-name }} \
          --set service.type=${{ inputs.service-type }} \
          --set service.port=${{ inputs.service-port }} \
          --set service.targetPort=${{ inputs.service-target-port }} \
          --set image.repository=${{ env.IMAGE_REPOSITORY }}/${{ inputs.app-name }} \
          --set image.tag=${{ inputs.image-tag-prefix }}${{ steps.vars.outputs.sha_short }} \
          --set "ingress.enabled=true,ingress.hosts[0].host=${{ inputs.k8s-ingress-name }},ingress.hosts[0].paths[0].path=/,ingress.hosts[0].paths[0].pathType=ImplementationSpecific" \
          --set "ingress.tls[0].secretName=${{ inputs.k8s-ingress-tls-name }},ingress.tls[0].hosts[0]=${{ inputs.k8s-ingress-name }}"
