name: Build and Deploy Service

on:
  workflow_call:
    inputs:
      build-path:
        description: "Maps to the docker file BUILD_PATH argument"
        required: true
        type: string
      build-profile:
        description: "Maps to the docker file BUILD_PROFILE argument"
        required: true
        type: string
      app-name:
        description: "The app's name."
        required: true
        type: string
      tag-prefix:
        description: "Prefix used for docker image tag."
        required: true
        type: string
      k8s-deployment-ns:
        description: "Kubernetes deployment namespace"
        required: true
        type: string
      k8s-ingress-suffix:
        description: "Kubernetes ingress suffix"
        required: true
        type: string
      k8s-ingress-tls-name:
        description: "Kubernetes ingress TLS name"
        required: true
        type: string

jobs:
  import_deploy_info:
    runs-on: ubuntu-latest
    name: Import Deploy Info
    id: import_deploy_info
    outputs:
      deploy_info: ${{ steps.export-json.outputs.deploy_info }}
    steps:
      - name: Read In Deploy File
        id: read-file
        uses: juliangruber/read-file-action@v1
        with:
          path: ./${{ inputs.app-name }}/deploy_info.json
      - name: Export Deploy Json
        id: export-json
        run: |
          content=$(echo ${{ steps.read-file.outputs.content }})
          content="${content//'%'/'%25'}"
          content="${content//$'\n'/'%0A'}"
          content="${content//$'\r'/'%0D'}"
          echo "::set-output name=deploy_info::$content"
  build_docker:
    needs: [ import_deploy_info ]
    name: Build and Push Docker Image
    secrets: inherit
    uses: ./.github/workflows/docker-build.yaml
    with:
      dockerfile: ${{ fromJson(needs.import_deploy_info.outputs.deploy_info).dockerfile }}
      build-path: ${{ inputs.build-path }}
      build-profile: ${{ inputs.build-profile }}
      app-name: ${{ inputs.app-name }}
      tag-prefix: ${{ inputs.tag-prefix }}
  deploy_kube:
    needs: [ import_deploy_info, build_docker ]
    name: Deploy Service to Kubernetes
    secrets: inherit
    uses: ./.github/workflows/deploy-kubernetes.yaml
    with:
      app-name: ${{ inputs.app-name }}
      helm-chart: ${{ fromJson(needs.import_deploy_info.outputs.deploy_info).chart }}
      tag-prefix: ${{ inputs.tag-prefix }}
      k8s-deployment-ns: ${{ inputs.k8s-deployment-ns }}
      k8s-ingress-name: ${{ fromJson(needs.import_deploy_info.outputs.deploy_info).ingress-prefix }}${{ inputs.k8s-ingress-suffix }}
      k8s-ingress-tls-name: ${{ inputs.k8s-ingress-tls-name }}